[package]
name = "mina-recorder"
version = "0.1.0"
authors = ["Vladislav Melnik <vladislav.melnik@viablesystems.io>"]
edition = "2021"
rust-version = "1.58.1"
license = "MIT"

[build-dependencies]
prost-build = { version = "0.11.1" }

[dependencies]
log = { version = "0.4.17" }
hex = { version = "0.4.3" }
time = { version = "0.3.11", features = ["formatting"] }
unsigned-varint = { version = "0.7.1" }
multiaddr = { version = "0.14.0" }

prost = { version = "0.11.0" }
mina-p2p-messages = { git = "https://github.com/name-placeholder/mina-p2p-messages-rs.git", rev = "c53a65ccaea9a7880c075dc1a2494e66737977d1" }
binprot = { version = "0.1.7" }

salsa20 = { version = "0.10.2" }
blake2 = { version = "0.10.4" }
curve25519-dalek = { version = "3.2" }
sha2 = { version = "0.10.2" }
chacha20poly1305 = { version = "0.10.0" }
vru-noise = { version = "1.5" }

rocksdb = { version = "0.19.0", default-features = false }
radiation = { version = "0.2.1" }
thiserror = { version = "1.0.32" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
itertools = { version = "0.10.3" }

tokio = { version = "1.20", features = ["rt-multi-thread", "signal"] }
warp = { version = "0.3.2", features = ["tls"] }

libp2p-core = { version = "*" }
# ed25519-dalek = { version = "*" }
