[package]
name = "mina-recorder"
version = "0.1.0"
authors = ["Vladislav Melnik <vladislav.melnik@viablesystems.io>"]
edition = "2021"
rust-version = "1.58.1"
license = "MIT"

[dependencies]
log = { version = "0.4.17" }
hex = { version = "0.4.3" }
salsa20 = { version = "0.10.2" }
blake2 = { version = "0.10.4" }

curve25519-dalek = { version = "3.2" }
sha2 = { version = "0.10.2" }
chacha20poly1305 = { version = "0.9.1" }
vru-noise = { version = "1.4" }

# libp2p-core = { version = "*" }
# ed25519-dalek = { version = "*" }
