apiVersion: v1
kind: Service
metadata:
  name: registry-svc
spec:
  type: NodePort
  selector:
    app: mock-registry
  ports:
    - port: 80
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mock-registry
  name: mock-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mock-registry
  template:
    metadata:
      labels:
        app: mock-registry
    spec:
      # runtimeClassName: kata-qemu
      # shareProcessNamespace: true
      containers:
        - name: mock-registry
          image: vladsimplestakingcom/mina-tester-k:latest
          imagePullPolicy: Always
          env:
            - name: RUST_LOG
              value: debug
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: mock
  name: mock
spec:
  parallelism: {{ .Values.parallelism }}
  ttlSecondsAfterFinished: 0
  template:
    metadata:
      labels:
        app: mock
    spec:
      runtimeClassName: kata-qemu
      # shareProcessNamespace: true
      restartPolicy: Never
      containers:
        - name: bpf-debugger
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          securityContext:
            privileged: true
          command: ["sh", "-ce", "bpf-recorder"]
          env:
            - name: RUST_LOG
              value: "info"
            - name: SERVER_PORT
              value: "8000"
            - name: DEBUGGER_NAME
              value: "debugger"
            - name: REGISTRY
              value: "registry-svc"
            - name: TERMINATE
              value: "1"
            - name: BUILD_NUMBER
              value: "{{ .Values.build_number }}"
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          volumeMounts:
            - mountPath: /sys/kernel/debug
              name: sys-kernel-debug
            - mountPath: /proc
              name: proc
          # resources:
          #   requests:
          #     memory: 4G
          #   limits:
          #     memory: 8G
        - name: mock-node
          image: vladsimplestakingcom/mina-tester-k:latest
          imagePullPolicy: Always
          securityContext:
            privileged: true
          command: [ "sh", "-c" ]
          args:
            # TODO: wait registry is ready inside mina-tester-k process
            - |
              sleep 5
              mina-tester-k peer --blocks={{ .Values.blocks }} --delay={{ .Values.delay }}
          env:
            - name: "RUST_LOG"
              value: info
            - name: REGISTRY
              value: "registry-svc"
            - name: BUILD_NUMBER
              value: "{{ .Values.build_number }}"
            - name: BPF_ALIAS
              value: "/coda/0.0.1/00000000000000000000000066616b65206e6574776f726b00000000deadbeef-0.0.0.0"
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
      volumes:
        - name: sys-kernel-debug
          hostPath:
            path: /sys/kernel/debug
        - name: proc
          hostPath:
            path: /proc
---
